### ISSUE TITLE
LaTex issue

### ISSUE THREAD

**Issue by yun-goon** [hytric/hytric.github.io#1]
https://github.com/hytric/hytric.github.io/commit/9ff073bd8d8b9e14908052c834f2454d28cab5a6#diff-91c15c207aa9ba2d52f492255d9c214d0e80bf198a40f30b3ab6178965216853R86 
![image](https://github.com/user-attachments/assets/98d57741-e5bb-4d98-afd3-3d3c7197eeb8)
https://hytric.github.io/paperreview/PersoninPlace/#feature-extraction
It doesn't come out properly.

**Comment by hytric** [comment]
now you can see properly
