### ISSUE TITLE
LaTex issue 2

### ISSUE THREAD

**Issue by yun-goon** [hytric/hytric.github.io#2]
https://hytric.github.io/paperreview/diffusionDesignSpace/#denoising-score-matching
![image](https://github.com/user-attachments/assets/379ff861-d851-49a6-92d6-8e962bec60a3)
https://github.com/hytric/hytric.github.io/commit/7a44de518b5810f65d9acbc0c7df553bf48e5f47#diff-d0ec4b914682b122fcfdad958223c2516a5db8190b28ea7ba1ffdfeacbdbc5b6R124

here. check plz.

**Comment by hytric** [comment]
@yun-goon, thanks for raising this issue
now you can see properly
